version: '3.8'

services:
        postgres:
                image: postgres:15-alpine
                container_name: real_bank_postgres
                environment:
                        POSTGRES_DB: javaisland_backend
                        POSTGRES_USER: bank_admin
                        POSTGRES_PASSWORD: bank_password
                ports:
                        - "5432:5432"
                volumes:
                        - postgres_data:/var/lib/postgresql/data

        keycloak:
                image: quay.io/keycloak/keycloak:24.0
                container_name: real_bank_keycloak
                command: start-dev
                environment:
                        KEYCLOAK_ADMIN: admin
                        KEYCLOAK_ADMIN_PASSWORD: admin
                ports:
                        - "8080:8080"
                depends_on:
                        - postgres

volumes:
        postgres_data: