spring:
  application:
    name: bank-backend

  # 💾 CONFIGURAZIONE DEL DATABASE POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/javaisland_bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # 🛠️ CONFIGURAZIONE HIBERNATE / JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 🔌 CONFIGURAZIONE DELLA PORTA DEL SERVER TOMCAT
server:
  port: 8080