server.port=8081
spring.application.name=bank-backend

# Connessione a PostgreSQL usando l'utente nativo root
spring.datasource.url=jdbc:postgresql://localhost:5432/javaisland_backend
spring.datasource.username=postgres
spring.datasource.password=bank_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect